title = "bunnysocks"
# The URL the site will be built for
base_url = "https://bunnysocks.github.io"
description = "Opinionated, modern, pretty, and clean Zola theme."

theme = "duckquill"

compile_sass = true
minify_html = true
generate_feeds = true
# Only the first file will be used in the navbar feed button,
# other feeds will still be available in page's head.
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "Heman Sakkthivel"

# Based on https://github.com/welpo/tabi
#
# To translate the entire theme, there must be a file with the same ISO 639-1 or BCP 47
# language code in the `i18n` directory of your site or the Duckquill theme.
# For example, "i18n/fr.toml" for French or "i18n/zh-Hans.toml" for Simplified Chinese.
# Otherwise the theme will be in English.
#
# ISO 639-1: https://localizely.com/iso-639-1-list/
# BCP 47: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "solarized-dark", filename = "syntax-theme-dark.css" },
	{ theme = "solarized-light", filename = "syntax-theme-light.css" }
]
smart_punctuation = true
bottom_footnotes = true

[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"



[extra]

favicon = "favicon.png"
# Which theme should be used by default (light/dark).
#
# default_theme = "dark"
#
# Sets theme and browser theme color.
# See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
accent_color = "#4A63D9"        # deep periwinkle
accent_color_dark = "#8EA2FF"   # cool luminous tint
# Whether to use fonts bundled with Duckquill instead of system ones.
# Keep in mind that it also changes the style of headings.
#
# bundled_fonts = true
#
# Use emoji as a favicon.
# Only one emoji is being rendered, everything else is truncated.
#
# emoji_favicon = "ðŸ¦†ðŸª¶"
#
# URL to website's issue tracker
issues_url = "https://codeberg.org/daudix/duckquill/issues"
# URL to website's source code
source_url = "https://codeberg.org/daudix/duckquill"
# Additional CSS styles; expects them to be in the "./static/" directory.
# If you are using Sass it will be generated there automatically.
#
styles = ["custom.css"]
#
# Additional JavaScript scripts; expects them to be in the "./static/" directory.
#
# scripts = [
#   "YOUR_SCRIPT.js",
#   "ALSO_YOUR_SCRIPT.js"
# ]
#
# Whether to show "copy code" button on all code blocks
# that have the language set.
# See https://www.getzola.org/documentation/content/syntax-highlighting/
show_copy_button = true
# Whether to show estimated read time in posts.
show_reading_time = true
#
# Whether to show a share button in article's quick actions.
# Uses https://shareopenly.org.
show_share_button = true
# Whether to show the backlinks button for linked articles in the article's quick actions
show_backlinks = true
# Whether to enable the KaTeX library for rendering LaTeX.
# Note: This will make your page significantly heavier.
# Instead, consider enabling it per page/section.
# katex = true
#
# Whether to render table of contents on all pages.
# Will not be rendered if page doesn't have any headings.
# Can be set per page/section.
# toc = true
#
# Whether to render inline table of contents at the top of all pages,
# in addition to floating quick navigation buttons.
# Can be set per page/section.
# toc_inline = true
#
# Whether to use numbered (ordered) list for table of contents.
# Can be set per page/section.
# toc_ordered = true
#
# Custom separator used across the theme.
# separator = "â€¢"
# Custom separator used in title tag and posts metadata.
# title_separator = "-"
#
# Whether to use Content Security Policy.
# Keep in mind that although this can potentially increase security,
# it can break some stuff, in which case you will need to set custom policy.
csp = [
	{ directive = "font-src", domains = ["'self'"] },
	{ directive = "img-src", domains = ["'self'", "https:", "data:"] },
	{ directive = "media-src", domains = ["'self'", "https:"] },
	{ directive = "script-src", domains = ["'self'"] },
	{ directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
	{ directive = "frame-src", domains = ["https://player.vimeo.com", "https://www.youtube-nocookie.com", "https://toot.community"] },
	{ directive = "connect-src", domains = ["https://toot.community"] },
	{ directive = "base-uri", domains = ["'none'"] },
	{ directive = "form-action", domains = ["'none'"] }
]
# Uncomment this to disable the card displayed in share previews
# card = false

[extra.nav]
# Whether to automatically hide nav when not hovered or focused
# auto_hide = true
# Whether to show the Atom/RSS feed button in the nav
show_feed = true
# Whether to show the manual theme switcher in the nav
show_theme_switcher = true
# Whether to show the link to the source repository in the nav
show_repo = false
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e. "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
    { url = "@/blog/_index.md", name = "Blog" },
    { url = "@/resume/_index.md", name = "Resume" },
	{ url = "@/contact/index.md", name = "Contact" },
]

[extra.footer]
# Links used in the footer.
# Same as the nav ones.
# Social links in the footer.
# Any URL-encoded SVG can be used as an icon.
# https://simpleicons.org is the recommended source of SVG icons.
# For URL encoding use https://yoksel.github.io/url-encoder/.
# Make sure that "external quotes" are set to "double".
# Whether to show "Â© Title, YEAR"
show_copyright = true
# Whether to show "Powered by Zola and Duckquill"
show_powered_by = false
# Whether to show link to website source
show_source = false
# Custom copyright text
#
copyright = "Â© bunnysocks,`2025`"

# Based on https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/
#
# Mastodon-powered commenting.
# Values can be overridden in the front-matter, e.g.
# for multi-author blogs or guest posts.
#
# These variables are also used for Mastodon verification,
# the needed rel="me" link is set in the head based on these.
[extra.comments]
# Your Mastodon API host; instance that you have an account on.
host = "vmst.io"
# Your Mastodon username; used to determine who the original poster is.
user = "daudix"
# Whether to show the QR code to Mastodon post
show_qr = true

# GoatCounter analytics; enabled only if present in config.
[extra.goatcounter]
# Your GoatCounter server; goatcounter.com is used by default.
#
# host = "YOUR_SERVER"
#
# Your GoatCounter username
user = "bunnysocks"

[extra.debug]
# Display outlines around all elements for debugging purposes
layout = false
# Don't load any styles for debugging purposes
no_styles = false
